# generated
name: xivcg2vj5vhu42hnb
on:
  workflow_dispatch:
    inputs:
      x2vqw4hj45wpi775d:
        type: string
        required: true
  workflow_call:
    inputs:
      x2vqw4hj45wpi775d:
        type: string
        required: true
permissions: {}
jobs:
  xjilk5xoyaizv2pia:
    runs-on: ubuntu-24.04
    timeout-minutes: 360
    permissions:
      actions: write
      contents: read
      id-token: write
    outputs:
      xjtwrjwdzszxvmqn5: ${{ steps.run.outputs.xjtwrjwdzszxvmqn5 }}
      xqhzrjftie2gdj3z7: ${{ steps.run.outputs.xqhzrjftie2gdj3z7 }}
      xygezsllgoy73kn53: ${{ steps.run.outputs.xygezsllgoy73kn53 }}
    steps:
      - id: setup
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false
      - id: run
        env:
          GITHUB_TOKEN: ${{ github.token }}
          xn3zr7llogolq2cub: ${{ secrets.xrvbdflruaymvxxzf }}
          xrnofjcthpc4qmbz7: ${{ secrets.xbltcnyaeqb2gre7e }}
          xzvqnm43i5urhuo64: ${{ secrets.xqpqccuz4ji3yaemy }}
          x2uu7eyolekmt4x6v: xxxjslkw6j4gbaahu
          xddmforgnxqdgpnmy: xjtwrjwdzszxvmqn5,xqhzrjftie2gdj3z7,xygezsllgoy73kn53
          x2vqw4hj45wpi775d: ${{ inputs.x2vqw4hj45wpi775d }}
          xjrftuyyzydfdnhuv: ${{ secrets.xrgkh2ukj24pii3dd }}
          xea77mrl3yo2ajq4z: ${{ secrets.xuvu5arjlpainoj3r }}
          xpbxqpudtraqnw4pv: ${{ secrets.xtiwyhxzvgmz7aubs }}
          xeadwiifs2yqqofda: ${{ secrets.xe3uu2zu57hujq2fr }}
          xeyl3mdb4c5aeowe7: ${{ secrets.xwj33yvzevqs75t4h }}
          x4lb2rlicps2lhdl7: ${{ secrets.xpijl5yt3k6bwdpez }}
          xf4e4wdneoij4cjx7: ${{ secrets.xohaqlvexbottgtug }}
        run: ./.github/bin/xivcg2vj5vhu42hnb
  xecjxcxmxky5k4ofh:
    runs-on: ubuntu-24.04
    timeout-minutes: 360
    permissions:
      actions: write
      contents: read
      id-token: write
    needs:
      - xjilk5xoyaizv2pia
    outputs:
      xywp4v7adihlkqrgt: ${{ steps.run.outputs.xywp4v7adihlkqrgt }}
    steps:
      - id: setup
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false
      - id: run
        env:
          GITHUB_TOKEN: ${{ github.token }}
          xn3zr7llogolq2cub: ${{ secrets.xrvbdflruaymvxxzf }}
          xrnofjcthpc4qmbz7: ${{ secrets.xbltcnyaeqb2gre7e }}
          xzvqnm43i5urhuo64: ${{ secrets.xqpqccuz4ji3yaemy }}
          x2uu7eyolekmt4x6v: xkyafin5jy646v2qy
          xddmforgnxqdgpnmy: xywp4v7adihlkqrgt
          x6vnmn5dybaitmryv: ${{ needs.xjilk5xoyaizv2pia.outputs.xygezsllgoy73kn53 }}
          xjrftuyyzydfdnhuv: ${{ secrets.xrgkh2ukj24pii3dd }}
          xea77mrl3yo2ajq4z: ${{ secrets.xuvu5arjlpainoj3r }}
          xeadwiifs2yqqofda: ${{ secrets.xe3uu2zu57hujq2fr }}
          xeyl3mdb4c5aeowe7: ${{ secrets.xwj33yvzevqs75t4h }}
          x4lb2rlicps2lhdl7: ${{ secrets.xpijl5yt3k6bwdpez }}
          xf4e4wdneoij4cjx7: ${{ secrets.xohaqlvexbottgtug }}
        run: ./.github/bin/xivcg2vj5vhu42hnb
  xn5rmmlnvxxiajzva:
    runs-on: ubuntu-24.04
    timeout-minutes: 360
    permissions:
      actions: write
      contents: read
      id-token: write
    needs:
      - xjilk5xoyaizv2pia
      - xecjxcxmxky5k4ofh
    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        xvijbjvtzsiphpxns: ${{ fromJSON(needs.xecjxcxmxky5k4ofh.outputs.xywp4v7adihlkqrgt) }}
    steps:
      - id: setup
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false
      - id: run
        env:
          GITHUB_TOKEN: ${{ github.token }}
          xn3zr7llogolq2cub: ${{ secrets.xrvbdflruaymvxxzf }}
          xrnofjcthpc4qmbz7: ${{ secrets.xbltcnyaeqb2gre7e }}
          xzvqnm43i5urhuo64: ${{ secrets.xqpqccuz4ji3yaemy }}
          x2uu7eyolekmt4x6v: xftuj3cdjjeox2jrz
          xddmforgnxqdgpnmy: ''
          x7yjivpqmrgj5oi5h: ${{ matrix.xvijbjvtzsiphpxns }}
          xafatceh6p5sxwekj: ${{ needs.xjilk5xoyaizv2pia.outputs.xjtwrjwdzszxvmqn5 }}
          xw2asf2isynuijchl: ${{ needs.xjilk5xoyaizv2pia.outputs.xygezsllgoy73kn53 }}
          xykqgahhc2as3bdt6: ${{ needs.xjilk5xoyaizv2pia.outputs.xqhzrjftie2gdj3z7 }}
          xjrftuyyzydfdnhuv: ${{ secrets.xrgkh2ukj24pii3dd }}
          xea77mrl3yo2ajq4z: ${{ secrets.xuvu5arjlpainoj3r }}
          xpbxqpudtraqnw4pv: ${{ secrets.xtiwyhxzvgmz7aubs }}
          xeadwiifs2yqqofda: ${{ secrets.xe3uu2zu57hujq2fr }}
          xeyl3mdb4c5aeowe7: ${{ secrets.xwj33yvzevqs75t4h }}
          x4lb2rlicps2lhdl7: ${{ secrets.xpijl5yt3k6bwdpez }}
          xf4e4wdneoij4cjx7: ${{ secrets.xohaqlvexbottgtug }}
        run: ./.github/bin/xivcg2vj5vhu42hnb
  xpbneetkpyiy46j4d:
    runs-on: ubuntu-24.04
    timeout-minutes: 360
    permissions:
      actions: write
      contents: read
      id-token: write
    needs:
      - xjilk5xoyaizv2pia
      - xn5rmmlnvxxiajzva
    if: ${{ always() }}
    steps:
      - id: setup
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false
      - id: run
        env:
          GITHUB_TOKEN: ${{ github.token }}
          xn3zr7llogolq2cub: ${{ secrets.xrvbdflruaymvxxzf }}
          xrnofjcthpc4qmbz7: ${{ secrets.xbltcnyaeqb2gre7e }}
          xzvqnm43i5urhuo64: ${{ secrets.xqpqccuz4ji3yaemy }}
          x2uu7eyolekmt4x6v: xbtybhjybcgpt6zmf
          xddmforgnxqdgpnmy: ''
          x2dyocuwgdfqhzqkh: ${{ needs.xn5rmmlnvxxiajzva.result }}
          xf7k735lfzu36hch3: ${{ needs.xjilk5xoyaizv2pia.outputs.xqhzrjftie2gdj3z7 }}
          xnwm5ioydgoqd7scv: ${{ needs.xjilk5xoyaizv2pia.outputs.xjtwrjwdzszxvmqn5 }}
          xta3mt3e4te2ibzvc: ${{ needs.xjilk5xoyaizv2pia.outputs.xygezsllgoy73kn53 }}
          xjrftuyyzydfdnhuv: ${{ secrets.xrgkh2ukj24pii3dd }}
          xea77mrl3yo2ajq4z: ${{ secrets.xuvu5arjlpainoj3r }}
          xeadwiifs2yqqofda: ${{ secrets.xe3uu2zu57hujq2fr }}
          xeyl3mdb4c5aeowe7: ${{ secrets.xwj33yvzevqs75t4h }}
          x4lb2rlicps2lhdl7: ${{ secrets.xpijl5yt3k6bwdpez }}
          xf4e4wdneoij4cjx7: ${{ secrets.xohaqlvexbottgtug }}
        run: ./.github/bin/xivcg2vj5vhu42hnb
concurrency:
  group: xivcg2vj5vhu42hnb
  cancel-in-progress: false
