# generated
name: xivcg2vj5vh
on:
  workflow_dispatch:
    inputs:
      x2vqw4hj45w:
        type: string
        required: true
  workflow_call:
    inputs:
      x2vqw4hj45w:
        type: string
        required: true
permissions: {}
jobs:
  xjilk5xoyai:
    runs-on: ubuntu-24.04
    permissions:
      actions: write
      contents: read
      id-token: write
    outputs:
      xjtwrjwdzsz: ${{ steps.run.outputs.xjtwrjwdzsz }}
      xqhzrjftie2: ${{ steps.run.outputs.xqhzrjftie2 }}
      xygezsllgoy: ${{ steps.run.outputs.xygezsllgoy }}
    steps:
      - id: setup
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false
      - id: run
        env:
          GITHUB_TOKEN: ${{ github.token }}
          xn3zr7llogo: ${{ secrets.xrvbdflruay }}
          xrnofjcthpc: ${{ secrets.xbltcnyaeqb }}
          xzvqnm43i5u: ${{ secrets.xqpqccuz4ji }}
          x2uu7eyolek: xxxjslkw6j4
          xddmforgnxq: xjtwrjwdzsz,xqhzrjftie2,xygezsllgoy
          x2vqw4hj45w: ${{ inputs.x2vqw4hj45w }}
          xjrftuyyzyd: ${{ secrets.xrgkh2ukj24 }}
          xea77mrl3yo: ${{ secrets.xuvu5arjlpa }}
          xpbxqpudtra: ${{ secrets.xtiwyhxzvgm }}
          xeadwiifs2y: ${{ secrets.xe3uu2zu57h }}
          xeyl3mdb4c5: ${{ secrets.xwj33yvzevq }}
          x4lb2rlicps: ${{ secrets.xpijl5yt3k6 }}
          xf4e4wdneoi: ${{ secrets.xohaqlvexbo }}
        run: ./.github/bin/xivcg2vj5vh
  xecjxcxmxky:
    runs-on: ubuntu-24.04
    permissions:
      actions: write
      contents: read
      id-token: write
    needs:
      - xjilk5xoyai
    outputs:
      xywp4v7adih: ${{ steps.run.outputs.xywp4v7adih }}
    steps:
      - id: setup
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false
      - id: run
        env:
          GITHUB_TOKEN: ${{ github.token }}
          xn3zr7llogo: ${{ secrets.xrvbdflruay }}
          xrnofjcthpc: ${{ secrets.xbltcnyaeqb }}
          xzvqnm43i5u: ${{ secrets.xqpqccuz4ji }}
          x2uu7eyolek: xkyafin5jy6
          xddmforgnxq: xywp4v7adih
          x6vnmn5dyba: ${{ needs.xjilk5xoyai.outputs.xygezsllgoy }}
          xjrftuyyzyd: ${{ secrets.xrgkh2ukj24 }}
          xea77mrl3yo: ${{ secrets.xuvu5arjlpa }}
          xeadwiifs2y: ${{ secrets.xe3uu2zu57h }}
          xeyl3mdb4c5: ${{ secrets.xwj33yvzevq }}
          x4lb2rlicps: ${{ secrets.xpijl5yt3k6 }}
          xf4e4wdneoi: ${{ secrets.xohaqlvexbo }}
        run: ./.github/bin/xivcg2vj5vh
  xn5rmmlnvxx:
    runs-on: ubuntu-24.04
    permissions:
      actions: write
      contents: read
      id-token: write
    needs:
      - xjilk5xoyai
      - xecjxcxmxky
    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        xvijbjvtzsi: ${{ fromJSON(needs.xecjxcxmxky.outputs.xywp4v7adih) }}
    steps:
      - id: setup
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false
      - id: run
        env:
          GITHUB_TOKEN: ${{ github.token }}
          xn3zr7llogo: ${{ secrets.xrvbdflruay }}
          xrnofjcthpc: ${{ secrets.xbltcnyaeqb }}
          xzvqnm43i5u: ${{ secrets.xqpqccuz4ji }}
          x2uu7eyolek: xftuj3cdjje
          xddmforgnxq: ''
          x7yjivpqmrg: ${{ matrix.xvijbjvtzsi }}
          xafatceh6p5: ${{ needs.xjilk5xoyai.outputs.xjtwrjwdzsz }}
          xw2asf2isyn: ${{ needs.xjilk5xoyai.outputs.xygezsllgoy }}
          xykqgahhc2a: ${{ needs.xjilk5xoyai.outputs.xqhzrjftie2 }}
          xjrftuyyzyd: ${{ secrets.xrgkh2ukj24 }}
          xea77mrl3yo: ${{ secrets.xuvu5arjlpa }}
          xpbxqpudtra: ${{ secrets.xtiwyhxzvgm }}
          xeadwiifs2y: ${{ secrets.xe3uu2zu57h }}
          xeyl3mdb4c5: ${{ secrets.xwj33yvzevq }}
          x4lb2rlicps: ${{ secrets.xpijl5yt3k6 }}
          xf4e4wdneoi: ${{ secrets.xohaqlvexbo }}
        run: ./.github/bin/xivcg2vj5vh
  xpbneetkpyi:
    runs-on: ubuntu-24.04
    permissions:
      actions: write
      contents: read
      id-token: write
    needs:
      - xjilk5xoyai
      - xn5rmmlnvxx
    if: ${{ always() }}
    steps:
      - id: setup
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false
      - id: run
        env:
          GITHUB_TOKEN: ${{ github.token }}
          xn3zr7llogo: ${{ secrets.xrvbdflruay }}
          xrnofjcthpc: ${{ secrets.xbltcnyaeqb }}
          xzvqnm43i5u: ${{ secrets.xqpqccuz4ji }}
          x2uu7eyolek: xbtybhjybcg
          xddmforgnxq: ''
          x2dyocuwgdf: ${{ needs.xn5rmmlnvxx.result }}
          xf7k735lfzu: ${{ needs.xjilk5xoyai.outputs.xqhzrjftie2 }}
          xnwm5ioydgo: ${{ needs.xjilk5xoyai.outputs.xjtwrjwdzsz }}
          xta3mt3e4te: ${{ needs.xjilk5xoyai.outputs.xygezsllgoy }}
          xjrftuyyzyd: ${{ secrets.xrgkh2ukj24 }}
          xea77mrl3yo: ${{ secrets.xuvu5arjlpa }}
          xeadwiifs2y: ${{ secrets.xe3uu2zu57h }}
          xeyl3mdb4c5: ${{ secrets.xwj33yvzevq }}
          x4lb2rlicps: ${{ secrets.xpijl5yt3k6 }}
          xf4e4wdneoi: ${{ secrets.xohaqlvexbo }}
        run: ./.github/bin/xivcg2vj5vh
concurrency:
  group: xivcg2vj5vh
  cancel-in-progress: false
